name: CI for Python

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading code
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Running tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v
